### ISSUE TITLE
Sprites: Ability to add textures to sprites

### ISSUE THREAD

**Issue by daanh432** [rpbpolis/spic-prj-api#6]
Het is (op dit moment) niet mogelijk om een sprite een texture te geven maar alleen een kleur. Hierdoor is het lastig om straks een game te maken die wat simpele pixelart gebruikt in plaats van flat colors.

**Comment by rpbpolis** [comment]
Goed punt! Ons doel is echter om een soort minimale API te bieden, waar overduidelijk nog vanalles aan ontbreekt. Jouw suggestie valt daar ook onder. De huidige API en klassendiagram bieden je echter voldoende houvast om te bepalen waar en hoe je dat kan toevoegen.
